### ISSUE TITLE
Fetching raw_text has been blocked

### ISSUE THREAD

**Issue by jnimety** [usnationalarchives/federal_register#16]
I'm not sure exactly when this started but we are no longer able to fetch raw_text:

Example:
```
3.0.2 :004 > FederalRegister::Document.find('2021-21960').raw_text
$HOME/.rvm/gems/ruby-3.0.2@redacted/gems/federal_register-0.7.7/lib/federal_register/document.rb:98:in `rescue in block (2 levels) in <class:Document>': "https://www.federalregister.gov/documents/full_text/text/2021/10/07/2021-21960.txt" (RuntimeError)
$HOME/.rvm/gems/ruby-3.0.2@redacted/gems/federal_register-0.7.7/lib/federal_register/client.rb:39:in `get': Please use APIs, rather than crawling site. Learn more at /developers (HTTParty::ResponseError)
```

**Comment by andrewcarpenter** [comment]
Access to raw_text has been restored. Thank you for reaching out.
